name: sample push main flow
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  job1:
    runs-on: ["self-hosted"]
    steps:
      - name: set-env
        run: |
          echo "Name=Chaitu" >> ${GITHUB_ENV}
          sleep 50
#