name: sample push main flow
on:
  push:
    branches:
      - "main"
jobs:
  job1:
    runs-on: ["self-host"]
    steps:
      - name: code-checkout
        uses: actions/checkout@v4
      - name: print
        run: |
          printenv
      - name: list
        run: |
          ls -la