name: sample push main flow
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ["self-hosted"]
    steps:
      - name: set-env
        run: |
          echo "Name=Chaitu" >> ${GITHUB_ENV}
      - name: access-env
        run: |
          echo "This is my name - ${Name}"
          echo "::add-mask::${Name}"
          echo "::debug:: Maked the variable"
          echo "This is my name - ${Name}"
          
