name: sample push main flow
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ["self-hosted"]
    steps:
      - name: set-env
        run: |
          echo "Name=Chaitu" >> ${GITHUB_ENV}

      - name: warning
        run: |
          echo "::warning file=app.js,line=1,col=5,endColumn=7,title=YOUR-TITLE::Missing semicolon"

      - name:
      - name: access-env
        run: |
          echo "This is my name - ${Name}"
          echo "::add-mask::${Name}"
          echo "::debug:: Maked the variable"
          echo "This is my name - ${Name}"
          
