name: sample pull request flow
on:
  pull_request:
    branches:
      - "main"
jobs:
  job1:
    runs-on: ["self-hosted"]
    steps:
      - name: code-checkout
        uses: actions/checkout@v4
      - name: print
        run: |
          printenv
      - name: list
        run: |
          ls -la
          
          exit 1
