name: sample pull request flow
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ["self-hosted"]
    steps:
      - name: code-checkout
        uses: actions/checkout@v4
      - name: prin
        run: |
          printenv
      - name: list
        run: |
          ls -la
          
          
